// <auto-generated />
namespace gig.hub.online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class overrideconvetionforgigs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(overrideconvetionforgigs));
        
        string IMigrationMetadata.Id
        {
            get { return "201709180433347_override-convetionforgigs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
